version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /tmp:/tmp
    expose:
      - "5000"
    command: uwsgi --ini app.ini

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/ssl
      - ./app:/var/www/mojastrona
      - /tmp:/tmp
    depends_on:
      - app

